// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package ltpi_data_channel_controller_csr_rdl_pkg;
    typedef struct {
        logic [7:0] next;
    } ltpi_data_channel_controller_csr_rdl__RESP_CMD__cmd__in_t;

    typedef struct {
        ltpi_data_channel_controller_csr_rdl__RESP_CMD__cmd__in_t cmd;
    } ltpi_data_channel_controller_csr_rdl__RESP_CMD__in_t;

    typedef struct {
        logic [7:0] next;
    } ltpi_data_channel_controller_csr_rdl__RESP_TAG__tag__in_t;

    typedef struct {
        ltpi_data_channel_controller_csr_rdl__RESP_TAG__tag__in_t tag;
    } ltpi_data_channel_controller_csr_rdl__RESP_TAG__in_t;

    typedef struct {
        logic [3:0] next;
    } ltpi_data_channel_controller_csr_rdl__RESP_BEN__ben__in_t;

    typedef struct {
        ltpi_data_channel_controller_csr_rdl__RESP_BEN__ben__in_t ben;
    } ltpi_data_channel_controller_csr_rdl__RESP_BEN__in_t;

    typedef struct {
        logic [3:0] next;
    } ltpi_data_channel_controller_csr_rdl__RESP_STATUS__status__in_t;

    typedef struct {
        ltpi_data_channel_controller_csr_rdl__RESP_STATUS__status__in_t status;
    } ltpi_data_channel_controller_csr_rdl__RESP_STATUS__in_t;

    typedef struct {
        logic [7:0] next;
    } ltpi_data_channel_controller_csr_rdl__RESP_ADDR0__addr__in_t;

    typedef struct {
        ltpi_data_channel_controller_csr_rdl__RESP_ADDR0__addr__in_t addr;
    } ltpi_data_channel_controller_csr_rdl__RESP_ADDR0__in_t;

    typedef struct {
        logic [7:0] next;
    } ltpi_data_channel_controller_csr_rdl__RESP_ADDR1__addr__in_t;

    typedef struct {
        ltpi_data_channel_controller_csr_rdl__RESP_ADDR1__addr__in_t addr;
    } ltpi_data_channel_controller_csr_rdl__RESP_ADDR1__in_t;

    typedef struct {
        logic [7:0] next;
    } ltpi_data_channel_controller_csr_rdl__RESP_ADDR2__addr__in_t;

    typedef struct {
        ltpi_data_channel_controller_csr_rdl__RESP_ADDR2__addr__in_t addr;
    } ltpi_data_channel_controller_csr_rdl__RESP_ADDR2__in_t;

    typedef struct {
        logic [7:0] next;
    } ltpi_data_channel_controller_csr_rdl__RESP_ADDR3__addr__in_t;

    typedef struct {
        ltpi_data_channel_controller_csr_rdl__RESP_ADDR3__addr__in_t addr;
    } ltpi_data_channel_controller_csr_rdl__RESP_ADDR3__in_t;

    typedef struct {
        logic [7:0] next;
    } ltpi_data_channel_controller_csr_rdl__RESP_DATA0__data__in_t;

    typedef struct {
        ltpi_data_channel_controller_csr_rdl__RESP_DATA0__data__in_t data;
    } ltpi_data_channel_controller_csr_rdl__RESP_DATA0__in_t;

    typedef struct {
        logic [7:0] next;
    } ltpi_data_channel_controller_csr_rdl__RESP_DATA1__data__in_t;

    typedef struct {
        ltpi_data_channel_controller_csr_rdl__RESP_DATA1__data__in_t data;
    } ltpi_data_channel_controller_csr_rdl__RESP_DATA1__in_t;

    typedef struct {
        logic [7:0] next;
    } ltpi_data_channel_controller_csr_rdl__RESP_DATA2__data__in_t;

    typedef struct {
        ltpi_data_channel_controller_csr_rdl__RESP_DATA2__data__in_t data;
    } ltpi_data_channel_controller_csr_rdl__RESP_DATA2__in_t;

    typedef struct {
        logic [7:0] next;
    } ltpi_data_channel_controller_csr_rdl__RESP_DATA3__data__in_t;

    typedef struct {
        ltpi_data_channel_controller_csr_rdl__RESP_DATA3__data__in_t data;
    } ltpi_data_channel_controller_csr_rdl__RESP_DATA3__in_t;

    typedef struct {
        logic next;
    } ltpi_data_channel_controller_csr_rdl__STATUS__response_ready__in_t;

    typedef struct {
        logic hwclr;
    } ltpi_data_channel_controller_csr_rdl__STATUS__response_read__in_t;

    typedef struct {
        logic next;
    } ltpi_data_channel_controller_csr_rdl__STATUS__request_ready__in_t;

    typedef struct {
        logic hwclr;
    } ltpi_data_channel_controller_csr_rdl__STATUS__request_write__in_t;

    typedef struct {
        ltpi_data_channel_controller_csr_rdl__STATUS__response_ready__in_t response_ready;
        ltpi_data_channel_controller_csr_rdl__STATUS__response_read__in_t response_read;
        ltpi_data_channel_controller_csr_rdl__STATUS__request_ready__in_t request_ready;
        ltpi_data_channel_controller_csr_rdl__STATUS__request_write__in_t request_write;
    } ltpi_data_channel_controller_csr_rdl__STATUS__in_t;

    typedef struct {
        ltpi_data_channel_controller_csr_rdl__RESP_CMD__in_t RESP_CMD;
        ltpi_data_channel_controller_csr_rdl__RESP_TAG__in_t RESP_TAG;
        ltpi_data_channel_controller_csr_rdl__RESP_BEN__in_t RESP_BEN;
        ltpi_data_channel_controller_csr_rdl__RESP_STATUS__in_t RESP_STATUS;
        ltpi_data_channel_controller_csr_rdl__RESP_ADDR0__in_t RESP_ADDR0;
        ltpi_data_channel_controller_csr_rdl__RESP_ADDR1__in_t RESP_ADDR1;
        ltpi_data_channel_controller_csr_rdl__RESP_ADDR2__in_t RESP_ADDR2;
        ltpi_data_channel_controller_csr_rdl__RESP_ADDR3__in_t RESP_ADDR3;
        ltpi_data_channel_controller_csr_rdl__RESP_DATA0__in_t RESP_DATA0;
        ltpi_data_channel_controller_csr_rdl__RESP_DATA1__in_t RESP_DATA1;
        ltpi_data_channel_controller_csr_rdl__RESP_DATA2__in_t RESP_DATA2;
        ltpi_data_channel_controller_csr_rdl__RESP_DATA3__in_t RESP_DATA3;
        ltpi_data_channel_controller_csr_rdl__STATUS__in_t STATUS;
    } ltpi_data_channel_controller_csr_rdl__in_t;

    typedef struct {
        logic [7:0] value;
    } ltpi_data_channel_controller_csr_rdl__REQ_CMD__cmd__out_t;

    typedef struct {
        ltpi_data_channel_controller_csr_rdl__REQ_CMD__cmd__out_t cmd;
    } ltpi_data_channel_controller_csr_rdl__REQ_CMD__out_t;

    typedef struct {
        logic [7:0] value;
    } ltpi_data_channel_controller_csr_rdl__REQ_TAG__tag__out_t;

    typedef struct {
        ltpi_data_channel_controller_csr_rdl__REQ_TAG__tag__out_t tag;
    } ltpi_data_channel_controller_csr_rdl__REQ_TAG__out_t;

    typedef struct {
        logic [3:0] value;
    } ltpi_data_channel_controller_csr_rdl__REQ_BEN__ben__out_t;

    typedef struct {
        ltpi_data_channel_controller_csr_rdl__REQ_BEN__ben__out_t ben;
    } ltpi_data_channel_controller_csr_rdl__REQ_BEN__out_t;

    typedef struct {
        logic [7:0] value;
    } ltpi_data_channel_controller_csr_rdl__REQ_ADDR0__addr__out_t;

    typedef struct {
        ltpi_data_channel_controller_csr_rdl__REQ_ADDR0__addr__out_t addr;
    } ltpi_data_channel_controller_csr_rdl__REQ_ADDR0__out_t;

    typedef struct {
        logic [7:0] value;
    } ltpi_data_channel_controller_csr_rdl__REQ_ADDR1__addr__out_t;

    typedef struct {
        ltpi_data_channel_controller_csr_rdl__REQ_ADDR1__addr__out_t addr;
    } ltpi_data_channel_controller_csr_rdl__REQ_ADDR1__out_t;

    typedef struct {
        logic [7:0] value;
    } ltpi_data_channel_controller_csr_rdl__REQ_ADDR2__addr__out_t;

    typedef struct {
        ltpi_data_channel_controller_csr_rdl__REQ_ADDR2__addr__out_t addr;
    } ltpi_data_channel_controller_csr_rdl__REQ_ADDR2__out_t;

    typedef struct {
        logic [7:0] value;
    } ltpi_data_channel_controller_csr_rdl__REQ_ADDR3__addr__out_t;

    typedef struct {
        ltpi_data_channel_controller_csr_rdl__REQ_ADDR3__addr__out_t addr;
    } ltpi_data_channel_controller_csr_rdl__REQ_ADDR3__out_t;

    typedef struct {
        logic [7:0] value;
    } ltpi_data_channel_controller_csr_rdl__REQ_DATA0__data__out_t;

    typedef struct {
        ltpi_data_channel_controller_csr_rdl__REQ_DATA0__data__out_t data;
    } ltpi_data_channel_controller_csr_rdl__REQ_DATA0__out_t;

    typedef struct {
        logic [7:0] value;
    } ltpi_data_channel_controller_csr_rdl__REQ_DATA1__data__out_t;

    typedef struct {
        ltpi_data_channel_controller_csr_rdl__REQ_DATA1__data__out_t data;
    } ltpi_data_channel_controller_csr_rdl__REQ_DATA1__out_t;

    typedef struct {
        logic [7:0] value;
    } ltpi_data_channel_controller_csr_rdl__REQ_DATA2__data__out_t;

    typedef struct {
        ltpi_data_channel_controller_csr_rdl__REQ_DATA2__data__out_t data;
    } ltpi_data_channel_controller_csr_rdl__REQ_DATA2__out_t;

    typedef struct {
        logic [7:0] value;
    } ltpi_data_channel_controller_csr_rdl__REQ_DATA3__data__out_t;

    typedef struct {
        ltpi_data_channel_controller_csr_rdl__REQ_DATA3__data__out_t data;
    } ltpi_data_channel_controller_csr_rdl__REQ_DATA3__out_t;

    typedef struct {
        logic value;
    } ltpi_data_channel_controller_csr_rdl__STATUS__response_read__out_t;

    typedef struct {
        logic value;
    } ltpi_data_channel_controller_csr_rdl__STATUS__request_write__out_t;

    typedef struct {
        ltpi_data_channel_controller_csr_rdl__STATUS__response_read__out_t response_read;
        ltpi_data_channel_controller_csr_rdl__STATUS__request_write__out_t request_write;
    } ltpi_data_channel_controller_csr_rdl__STATUS__out_t;

    typedef struct {
        ltpi_data_channel_controller_csr_rdl__REQ_CMD__out_t REQ_CMD;
        ltpi_data_channel_controller_csr_rdl__REQ_TAG__out_t REQ_TAG;
        ltpi_data_channel_controller_csr_rdl__REQ_BEN__out_t REQ_BEN;
        ltpi_data_channel_controller_csr_rdl__REQ_ADDR0__out_t REQ_ADDR0;
        ltpi_data_channel_controller_csr_rdl__REQ_ADDR1__out_t REQ_ADDR1;
        ltpi_data_channel_controller_csr_rdl__REQ_ADDR2__out_t REQ_ADDR2;
        ltpi_data_channel_controller_csr_rdl__REQ_ADDR3__out_t REQ_ADDR3;
        ltpi_data_channel_controller_csr_rdl__REQ_DATA0__out_t REQ_DATA0;
        ltpi_data_channel_controller_csr_rdl__REQ_DATA1__out_t REQ_DATA1;
        ltpi_data_channel_controller_csr_rdl__REQ_DATA2__out_t REQ_DATA2;
        ltpi_data_channel_controller_csr_rdl__REQ_DATA3__out_t REQ_DATA3;
        ltpi_data_channel_controller_csr_rdl__STATUS__out_t STATUS;
    } ltpi_data_channel_controller_csr_rdl__out_t;
endpackage